// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kheguy/collector/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name
func (_m *MockStorage) Get(ctx context.Context, name string) (interface{}, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStorage_Expecter) Get(ctx interface{}, name interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockStorage_Get_Call) Run(run func(ctx context.Context, name string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 interface{}, _a1 error) *MockStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockStorage) GetAll(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockStorage_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetAll(ctx interface{}) *MockStorage_GetAll_Call {
	return &MockStorage_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockStorage_GetAll_Call) Run(run func(ctx context.Context)) *MockStorage_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_GetAll_Call) Return(_a0 map[string]interface{}, _a1 error) *MockStorage_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetAll_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockStorage_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, name, mType, value
func (_m *MockStorage) Set(ctx context.Context, name string, mType string, value interface{}) error {
	ret := _m.Called(ctx, name, mType, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, name, mType, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - mType string
//   - value interface{}
func (_e *MockStorage_Expecter) Set(ctx interface{}, name interface{}, mType interface{}, value interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", ctx, name, mType, value)}
}

func (_c *MockStorage_Set_Call) Run(run func(ctx context.Context, name string, mType string, value interface{})) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(_a0 error) *MockStorage_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetAll provides a mock function with given fields: ctx, data
func (_m *MockStorage) SetAll(ctx context.Context, data map[string]interface{}) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAll'
type MockStorage_SetAll_Call struct {
	*mock.Call
}

// SetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - data map[string]interface{}
func (_e *MockStorage_Expecter) SetAll(ctx interface{}, data interface{}) *MockStorage_SetAll_Call {
	return &MockStorage_SetAll_Call{Call: _e.mock.On("SetAll", ctx, data)}
}

func (_c *MockStorage_SetAll_Call) Run(run func(ctx context.Context, data map[string]interface{})) *MockStorage_SetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *MockStorage_SetAll_Call) Return(_a0 error) *MockStorage_SetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SetAll_Call) RunAndReturn(run func(context.Context, map[string]interface{}) error) *MockStorage_SetAll_Call {
	_c.Call.Return(run)
	return _c
}

// SetBatch provides a mock function with given fields: ctx, metrics
func (_m *MockStorage) SetBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for SetBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SetBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBatch'
type MockStorage_SetBatch_Call struct {
	*mock.Call
}

// SetBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockStorage_Expecter) SetBatch(ctx interface{}, metrics interface{}) *MockStorage_SetBatch_Call {
	return &MockStorage_SetBatch_Call{Call: _e.mock.On("SetBatch", ctx, metrics)}
}

func (_c *MockStorage_SetBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockStorage_SetBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MockStorage_SetBatch_Call) Return(_a0 error) *MockStorage_SetBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SetBatch_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MockStorage_SetBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
