// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name, ctx
func (_m *MockStorage) Get(name string, ctx context.Context) (interface{}, error) {
	ret := _m.Called(name, ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (interface{}, error)); ok {
		return rf(name, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) interface{}); ok {
		r0 = rf(name, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(name, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
//   - ctx context.Context
func (_e *MockStorage_Expecter) Get(name interface{}, ctx interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", name, ctx)}
}

func (_c *MockStorage_Get_Call) Run(run func(name string, ctx context.Context)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 interface{}, _a1 error) *MockStorage_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(string, context.Context) (interface{}, error)) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockStorage) GetAll(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockStorage_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) GetAll(ctx interface{}) *MockStorage_GetAll_Call {
	return &MockStorage_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockStorage_GetAll_Call) Run(run func(ctx context.Context)) *MockStorage_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_GetAll_Call) Return(_a0 map[string]interface{}, _a1 error) *MockStorage_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetAll_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockStorage_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: name, mType, value, ctx
func (_m *MockStorage) Set(name string, mType string, value interface{}, ctx context.Context) error {
	ret := _m.Called(name, mType, value, ctx)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}, context.Context) error); ok {
		r0 = rf(name, mType, value, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - name string
//   - mType string
//   - value interface{}
//   - ctx context.Context
func (_e *MockStorage_Expecter) Set(name interface{}, mType interface{}, value interface{}, ctx interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", name, mType, value, ctx)}
}

func (_c *MockStorage_Set_Call) Run(run func(name string, mType string, value interface{}, ctx context.Context)) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}), args[3].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(_a0 error) *MockStorage_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(string, string, interface{}, context.Context) error) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetAll provides a mock function with given fields: data, ctx
func (_m *MockStorage) SetAll(data map[string]interface{}, ctx context.Context) error {
	ret := _m.Called(data, ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}, context.Context) error); ok {
		r0 = rf(data, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_SetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAll'
type MockStorage_SetAll_Call struct {
	*mock.Call
}

// SetAll is a helper method to define mock.On call
//   - data map[string]interface{}
//   - ctx context.Context
func (_e *MockStorage_Expecter) SetAll(data interface{}, ctx interface{}) *MockStorage_SetAll_Call {
	return &MockStorage_SetAll_Call{Call: _e.mock.On("SetAll", data, ctx)}
}

func (_c *MockStorage_SetAll_Call) Run(run func(data map[string]interface{}, ctx context.Context)) *MockStorage_SetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}), args[1].(context.Context))
	})
	return _c
}

func (_c *MockStorage_SetAll_Call) Return(_a0 error) *MockStorage_SetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_SetAll_Call) RunAndReturn(run func(map[string]interface{}, context.Context) error) *MockStorage_SetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
