// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with no fields
func (_m *MockService) GetAllMetrics() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockService_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockService_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
func (_e *MockService_Expecter) GetAllMetrics() *MockService_GetAllMetrics_Call {
	return &MockService_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics")}
}

func (_c *MockService_GetAllMetrics_Call) Run(run func()) *MockService_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetAllMetrics_Call) Return(_a0 map[string]interface{}) *MockService_GetAllMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetAllMetrics_Call) RunAndReturn(run func() map[string]interface{}) *MockService_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function with given fields: name
func (_m *MockService) GetMetric(name string) string {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockService_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockService_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - name string
func (_e *MockService_Expecter) GetMetric(name interface{}) *MockService_GetMetric_Call {
	return &MockService_GetMetric_Call{Call: _e.mock.On("GetMetric", name)}
}

func (_c *MockService_GetMetric_Call) Run(run func(name string)) *MockService_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetMetric_Call) Return(_a0 string) *MockService_GetMetric_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetMetric_Call) RunAndReturn(run func(string) string) *MockService_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawMetric provides a mock function with given fields: name
func (_m *MockService) GetRawMetric(name string) interface{} {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetRawMetric")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockService_GetRawMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawMetric'
type MockService_GetRawMetric_Call struct {
	*mock.Call
}

// GetRawMetric is a helper method to define mock.On call
//   - name string
func (_e *MockService_Expecter) GetRawMetric(name interface{}) *MockService_GetRawMetric_Call {
	return &MockService_GetRawMetric_Call{Call: _e.mock.On("GetRawMetric", name)}
}

func (_c *MockService_GetRawMetric_Call) Run(run func(name string)) *MockService_GetRawMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockService_GetRawMetric_Call) Return(_a0 interface{}) *MockService_GetRawMetric_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_GetRawMetric_Call) RunAndReturn(run func(string) interface{}) *MockService_GetRawMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: name, typeOfValue, value
func (_m *MockService) UpdateMetrics(name string, typeOfValue string, value interface{}) error {
	ret := _m.Called(name, typeOfValue, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(name, typeOfValue, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockService_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - name string
//   - typeOfValue string
//   - value interface{}
func (_e *MockService_Expecter) UpdateMetrics(name interface{}, typeOfValue interface{}, value interface{}) *MockService_UpdateMetrics_Call {
	return &MockService_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", name, typeOfValue, value)}
}

func (_c *MockService_UpdateMetrics_Call) Run(run func(name string, typeOfValue string, value interface{})) *MockService_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockService_UpdateMetrics_Call) Return(_a0 error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateMetrics_Call) RunAndReturn(run func(string, string, interface{}) error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
