// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with given fields: ctx
func (_m *MockService) GetAllMetrics(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockService_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAllMetrics(ctx interface{}) *MockService_GetAllMetrics_Call {
	return &MockService_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", ctx)}
}

func (_c *MockService_GetAllMetrics_Call) Run(run func(ctx context.Context)) *MockService_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetAllMetrics_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetAllMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllMetrics_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockService_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function with given fields: name, ctx
func (_m *MockService) GetMetric(name string, ctx context.Context) (string, error) {
	ret := _m.Called(name, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (string, error)); ok {
		return rf(name, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) string); ok {
		r0 = rf(name, ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(name, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockService_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - name string
//   - ctx context.Context
func (_e *MockService_Expecter) GetMetric(name interface{}, ctx interface{}) *MockService_GetMetric_Call {
	return &MockService_GetMetric_Call{Call: _e.mock.On("GetMetric", name, ctx)}
}

func (_c *MockService_GetMetric_Call) Run(run func(name string, ctx context.Context)) *MockService_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(context.Context))
	})
	return _c
}

func (_c *MockService_GetMetric_Call) Return(_a0 string, _a1 error) *MockService_GetMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetric_Call) RunAndReturn(run func(string, context.Context) (string, error)) *MockService_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawMetric provides a mock function with given fields: name, ctx
func (_m *MockService) GetRawMetric(name string, ctx context.Context) (interface{}, error) {
	ret := _m.Called(name, ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRawMetric")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string, context.Context) (interface{}, error)); ok {
		return rf(name, ctx)
	}
	if rf, ok := ret.Get(0).(func(string, context.Context) interface{}); ok {
		r0 = rf(name, ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string, context.Context) error); ok {
		r1 = rf(name, ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetRawMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawMetric'
type MockService_GetRawMetric_Call struct {
	*mock.Call
}

// GetRawMetric is a helper method to define mock.On call
//   - name string
//   - ctx context.Context
func (_e *MockService_Expecter) GetRawMetric(name interface{}, ctx interface{}) *MockService_GetRawMetric_Call {
	return &MockService_GetRawMetric_Call{Call: _e.mock.On("GetRawMetric", name, ctx)}
}

func (_c *MockService_GetRawMetric_Call) Run(run func(name string, ctx context.Context)) *MockService_GetRawMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(context.Context))
	})
	return _c
}

func (_c *MockService_GetRawMetric_Call) Return(_a0 interface{}, _a1 error) *MockService_GetRawMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetRawMetric_Call) RunAndReturn(run func(string, context.Context) (interface{}, error)) *MockService_GetRawMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: name, typeOfValue, value, ctx
func (_m *MockService) UpdateMetrics(name string, typeOfValue string, value interface{}, ctx context.Context) error {
	ret := _m.Called(name, typeOfValue, value, ctx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}, context.Context) error); ok {
		r0 = rf(name, typeOfValue, value, ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockService_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - name string
//   - typeOfValue string
//   - value interface{}
//   - ctx context.Context
func (_e *MockService_Expecter) UpdateMetrics(name interface{}, typeOfValue interface{}, value interface{}, ctx interface{}) *MockService_UpdateMetrics_Call {
	return &MockService_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", name, typeOfValue, value, ctx)}
}

func (_c *MockService_UpdateMetrics_Call) Run(run func(name string, typeOfValue string, value interface{}, ctx context.Context)) *MockService_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}), args[3].(context.Context))
	})
	return _c
}

func (_c *MockService_UpdateMetrics_Call) Return(_a0 error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateMetrics_Call) RunAndReturn(run func(string, string, interface{}, context.Context) error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
