// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSystemMetrics is an autogenerated mock type for the SystemMetrics type
type MockSystemMetrics struct {
	mock.Mock
}

type MockSystemMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemMetrics) EXPECT() *MockSystemMetrics_Expecter {
	return &MockSystemMetrics_Expecter{mock: &_m.Mock}
}

// CPUPercent provides a mock function with given fields: _a0
func (_m *MockSystemMetrics) CPUPercent(_a0 context.Context) ([]float64, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CPUPercent")
	}

	var r0 []float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]float64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []float64); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSystemMetrics_CPUPercent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CPUPercent'
type MockSystemMetrics_CPUPercent_Call struct {
	*mock.Call
}

// CPUPercent is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockSystemMetrics_Expecter) CPUPercent(_a0 interface{}) *MockSystemMetrics_CPUPercent_Call {
	return &MockSystemMetrics_CPUPercent_Call{Call: _e.mock.On("CPUPercent", _a0)}
}

func (_c *MockSystemMetrics_CPUPercent_Call) Run(run func(_a0 context.Context)) *MockSystemMetrics_CPUPercent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemMetrics_CPUPercent_Call) Return(_a0 []float64, _a1 error) *MockSystemMetrics_CPUPercent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSystemMetrics_CPUPercent_Call) RunAndReturn(run func(context.Context) ([]float64, error)) *MockSystemMetrics_CPUPercent_Call {
	_c.Call.Return(run)
	return _c
}

// VirtualMemory provides a mock function with given fields: _a0
func (_m *MockSystemMetrics) VirtualMemory(_a0 context.Context) (uint64, uint64, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VirtualMemory")
	}

	var r0 uint64
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) (uint64, uint64, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) uint64); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) uint64); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSystemMetrics_VirtualMemory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VirtualMemory'
type MockSystemMetrics_VirtualMemory_Call struct {
	*mock.Call
}

// VirtualMemory is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockSystemMetrics_Expecter) VirtualMemory(_a0 interface{}) *MockSystemMetrics_VirtualMemory_Call {
	return &MockSystemMetrics_VirtualMemory_Call{Call: _e.mock.On("VirtualMemory", _a0)}
}

func (_c *MockSystemMetrics_VirtualMemory_Call) Run(run func(_a0 context.Context)) *MockSystemMetrics_VirtualMemory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSystemMetrics_VirtualMemory_Call) Return(_a0 uint64, _a1 uint64, _a2 error) *MockSystemMetrics_VirtualMemory_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSystemMetrics_VirtualMemory_Call) RunAndReturn(run func(context.Context) (uint64, uint64, error)) *MockSystemMetrics_VirtualMemory_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSystemMetrics creates a new instance of MockSystemMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemMetrics {
	mock := &MockSystemMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
