// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/kheguy/collector/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetAllMetrics provides a mock function with given fields: ctx
func (_m *MockService) GetAllMetrics(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMetrics")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetAllMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllMetrics'
type MockService_GetAllMetrics_Call struct {
	*mock.Call
}

// GetAllMetrics is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetAllMetrics(ctx interface{}) *MockService_GetAllMetrics_Call {
	return &MockService_GetAllMetrics_Call{Call: _e.mock.On("GetAllMetrics", ctx)}
}

func (_c *MockService_GetAllMetrics_Call) Run(run func(ctx context.Context)) *MockService_GetAllMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetAllMetrics_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetAllMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetAllMetrics_Call) RunAndReturn(run func(context.Context) (map[string]interface{}, error)) *MockService_GetAllMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetric provides a mock function with given fields: ctx, name
func (_m *MockService) GetMetric(ctx context.Context, name string) (string, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMetric")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetric'
type MockService_GetMetric_Call struct {
	*mock.Call
}

// GetMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) GetMetric(ctx interface{}, name interface{}) *MockService_GetMetric_Call {
	return &MockService_GetMetric_Call{Call: _e.mock.On("GetMetric", ctx, name)}
}

func (_c *MockService_GetMetric_Call) Run(run func(ctx context.Context, name string)) *MockService_GetMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetMetric_Call) Return(_a0 string, _a1 error) *MockService_GetMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetMetric_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockService_GetMetric_Call {
	_c.Call.Return(run)
	return _c
}

// GetRawMetric provides a mock function with given fields: ctx, name
func (_m *MockService) GetRawMetric(ctx context.Context, name string) (interface{}, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRawMetric")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (interface{}, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) interface{}); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetRawMetric_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRawMetric'
type MockService_GetRawMetric_Call struct {
	*mock.Call
}

// GetRawMetric is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) GetRawMetric(ctx interface{}, name interface{}) *MockService_GetRawMetric_Call {
	return &MockService_GetRawMetric_Call{Call: _e.mock.On("GetRawMetric", ctx, name)}
}

func (_c *MockService_GetRawMetric_Call) Run(run func(ctx context.Context, name string)) *MockService_GetRawMetric_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetRawMetric_Call) Return(_a0 interface{}, _a1 error) *MockService_GetRawMetric_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetRawMetric_Call) RunAndReturn(run func(context.Context, string) (interface{}, error)) *MockService_GetRawMetric_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetrics provides a mock function with given fields: ctx, name, typeOfValue, value
func (_m *MockService) UpdateMetrics(ctx context.Context, name string, typeOfValue string, value interface{}) error {
	ret := _m.Called(ctx, name, typeOfValue, value)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, name, typeOfValue, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetrics'
type MockService_UpdateMetrics_Call struct {
	*mock.Call
}

// UpdateMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - typeOfValue string
//   - value interface{}
func (_e *MockService_Expecter) UpdateMetrics(ctx interface{}, name interface{}, typeOfValue interface{}, value interface{}) *MockService_UpdateMetrics_Call {
	return &MockService_UpdateMetrics_Call{Call: _e.mock.On("UpdateMetrics", ctx, name, typeOfValue, value)}
}

func (_c *MockService_UpdateMetrics_Call) Run(run func(ctx context.Context, name string, typeOfValue string, value interface{})) *MockService_UpdateMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *MockService_UpdateMetrics_Call) Return(_a0 error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateMetrics_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *MockService_UpdateMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetricsBatch provides a mock function with given fields: ctx, metrics
func (_m *MockService) UpdateMetricsBatch(ctx context.Context, metrics []models.Metrics) error {
	ret := _m.Called(ctx, metrics)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetricsBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metrics) error); ok {
		r0 = rf(ctx, metrics)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_UpdateMetricsBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetricsBatch'
type MockService_UpdateMetricsBatch_Call struct {
	*mock.Call
}

// UpdateMetricsBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - metrics []models.Metrics
func (_e *MockService_Expecter) UpdateMetricsBatch(ctx interface{}, metrics interface{}) *MockService_UpdateMetricsBatch_Call {
	return &MockService_UpdateMetricsBatch_Call{Call: _e.mock.On("UpdateMetricsBatch", ctx, metrics)}
}

func (_c *MockService_UpdateMetricsBatch_Call) Run(run func(ctx context.Context, metrics []models.Metrics)) *MockService_UpdateMetricsBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metrics))
	})
	return _c
}

func (_c *MockService_UpdateMetricsBatch_Call) Return(_a0 error) *MockService_UpdateMetricsBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_UpdateMetricsBatch_Call) RunAndReturn(run func(context.Context, []models.Metrics) error) *MockService_UpdateMetricsBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
