// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"

	pgx "github.com/jackc/pgx/v5"
)

// MockDBPool is an autogenerated mock type for the Pool type
type MockDBPool struct {
	mock.Mock
}

type MockDBPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBPool) EXPECT() *MockDBPool_Expecter {
	return &MockDBPool_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function with given fields: _a0
func (_m *MockDBPool) Begin(_a0 context.Context) (pgx.Tx, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBPool_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type MockDBPool_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDBPool_Expecter) Begin(_a0 interface{}) *MockDBPool_Begin_Call {
	return &MockDBPool_Begin_Call{Call: _e.mock.On("Begin", _a0)}
}

func (_c *MockDBPool_Begin_Call) Run(run func(_a0 context.Context)) *MockDBPool_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDBPool_Begin_Call) Return(_a0 pgx.Tx, _a1 error) *MockDBPool_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBPool_Begin_Call) RunAndReturn(run func(context.Context) (pgx.Tx, error)) *MockDBPool_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDBPool) Exec(_a0 context.Context, _a1 string, _a2 ...any) (pgconn.CommandTag, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _a2...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDBPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 ...any
func (_e *MockDBPool_Expecter) Exec(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockDBPool_Exec_Call {
	return &MockDBPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockDBPool_Exec_Call) Run(run func(_a0 context.Context, _a1 string, _a2 ...any)) *MockDBPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBPool_Exec_Call) Return(_a0 pgconn.CommandTag, _a1 error) *MockDBPool_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBPool_Exec_Call) RunAndReturn(run func(context.Context, string, ...any) (pgconn.CommandTag, error)) *MockDBPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDBPool) Query(_a0 context.Context, _a1 string, _a2 ...any) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _a2...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDBPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 ...any
func (_e *MockDBPool_Expecter) Query(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockDBPool_Query_Call {
	return &MockDBPool_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockDBPool_Query_Call) Run(run func(_a0 context.Context, _a1 string, _a2 ...any)) *MockDBPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBPool_Query_Call) Return(_a0 pgx.Rows, _a1 error) *MockDBPool_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBPool_Query_Call) RunAndReturn(run func(context.Context, string, ...any) (pgx.Rows, error)) *MockDBPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockDBPool) QueryRow(_a0 context.Context, _a1 string, _a2 ...any) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _a2...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// MockDBPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type MockDBPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 ...any
func (_e *MockDBPool_Expecter) QueryRow(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockDBPool_QueryRow_Call {
	return &MockDBPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockDBPool_QueryRow_Call) Run(run func(_a0 context.Context, _a1 string, _a2 ...any)) *MockDBPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBPool_QueryRow_Call) Return(_a0 pgx.Row) *MockDBPool_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBPool_QueryRow_Call) RunAndReturn(run func(context.Context, string, ...any) pgx.Row) *MockDBPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBPool creates a new instance of MockDBPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPool {
	mock := &MockDBPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
