// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name
func (_m *MockStorage) Get(name string) interface{} {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *MockStorage_Expecter) Get(name interface{}) *MockStorage_Get_Call {
	return &MockStorage_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *MockStorage_Get_Call) Run(run func(name string)) *MockStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStorage_Get_Call) Return(_a0 interface{}) *MockStorage_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Get_Call) RunAndReturn(run func(string) interface{}) *MockStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockStorage) GetAll() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockStorage_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockStorage_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockStorage_Expecter) GetAll() *MockStorage_GetAll_Call {
	return &MockStorage_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockStorage_GetAll_Call) Run(run func()) *MockStorage_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorage_GetAll_Call) Return(_a0 map[string]interface{}) *MockStorage_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_GetAll_Call) RunAndReturn(run func() map[string]interface{}) *MockStorage_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: name, mType, value
func (_m *MockStorage) Set(name string, mType string, value interface{}) interface{} {
	ret := _m.Called(name, mType, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, string, interface{}) interface{}); ok {
		r0 = rf(name, mType, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockStorage_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockStorage_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - name string
//   - mType string
//   - value interface{}
func (_e *MockStorage_Expecter) Set(name interface{}, mType interface{}, value interface{}) *MockStorage_Set_Call {
	return &MockStorage_Set_Call{Call: _e.mock.On("Set", name, mType, value)}
}

func (_c *MockStorage_Set_Call) Run(run func(name string, mType string, value interface{})) *MockStorage_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockStorage_Set_Call) Return(_a0 interface{}) *MockStorage_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Set_Call) RunAndReturn(run func(string, string, interface{}) interface{}) *MockStorage_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
