// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockRenderer is an autogenerated mock type for the Renderer type
type MockRenderer struct {
	mock.Mock
}

type MockRenderer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenderer) EXPECT() *MockRenderer_Expecter {
	return &MockRenderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function with given fields: w, name, data
func (_m *MockRenderer) Render(w http.ResponseWriter, name string, data interface{}) {
	_m.Called(w, name, data)
}

// MockRenderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type MockRenderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - name string
//   - data interface{}
func (_e *MockRenderer_Expecter) Render(w interface{}, name interface{}, data interface{}) *MockRenderer_Render_Call {
	return &MockRenderer_Render_Call{Call: _e.mock.On("Render", w, name, data)}
}

func (_c *MockRenderer_Render_Call) Run(run func(w http.ResponseWriter, name string, data interface{})) *MockRenderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockRenderer_Render_Call) Return() *MockRenderer_Render_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRenderer_Render_Call) RunAndReturn(run func(http.ResponseWriter, string, interface{})) *MockRenderer_Render_Call {
	_c.Run(run)
	return _c
}

// NewMockRenderer creates a new instance of MockRenderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenderer {
	mock := &MockRenderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
