with-expecter: true
issue-845-fix: true
dir: internal/mocks
outpkg: mocks
filename: "mock_{{.InterfaceName | snakecase}}.gen.go"
resolve-type-alias: false
disable-version-string: true
packages:
  github.com/kheguy/collector/internal/handler:
    interfaces:
      Service:
      Renderer:
      Pinger:
  github.com/kheguy/collector/internal/service:
    interfaces:
      Storage:
  github.com/kheguy/collector/internal/repository:
    config:
      dir: internal/mocks
      outpkg: mocks
    interfaces:
      Pool:
        config:
          filename: mock_db_pool.gen.go
          mockname: MockDBPool
  github.com/jackc/pgx/v5:
    config:
      dir: internal/mocks
      outpkg: mocks
    interfaces:
      Row:
        config:
          filename: mock_pgx_row.gen.go
          mockname: MockPGXRow
